// Generated by https://quicktype.io

namespace FiveSQD.Parallels.Entity.Schema.TwentyTwentyOne.One.Zero.SetEntityVisibility
{
    using System;

    using Newtonsoft.Json;

    public partial class SetEntityVisibility
    {
        [JsonProperty("entity-uuid", Required = Required.Always)]
        public Guid EntityUuid { get; set; }

        [JsonProperty("visible", Required = Required.Always)]
        public bool Visible { get; set; }
    }
}